clc;
clear;
image=imread("C:\Users\Shreyas\Desktop\Scilab\22f5b15c-396b-4200-aba9-6946cc097d33.jfif")
red=image(:,:,1)
green=image(:,:,2)
blue=image(:,:,3)
[yRed,x]=imhist(red)
[yGreen,x]=imhist(green)
[yBlue,x]=imhist(blue)
plot(x,yRed,'Red',x,yGreen,'Green',x,yBlue,'Blue')
